src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Num;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $heur_deb;

    /**
     * @ORM\Column(type="time", nullable=true)
     */
    private $heur_fin;


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->Address;
    }

    public function setAddress(string $Address): self
    {
        $this->Address = $Address;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getNum(): ?string
    {
        return $this->Num;
    }

    public function setNum(string $Num): self
    {
        $this->Num = $Num;

        return $this;
    }

    public function getHeurDeb(): ?\DateTimeInterface
    {
        return $this->heur_deb;
    }

    public function setHeurDeb(?\DateTimeInterface $heur_deb): self
    {
        $this->heur_deb = $heur_deb;

        return $this;
    }

    public function getHeurFin(): ?\DateTimeInterface
    {
        return $this->heur_fin;
    }

    public function setHeurFin(?\DateTimeInterface $heur_fin): self
    {
        $this->heur_fin = $heur_fin;

        return $this;
    }




}

src/Controller/admin/AdminPropertyController.php
<?php

namespace App\Controller\admin;

use App\Form\PropertyType;
use App\Entity\Property;
use App\Repository\PropertyRepository;
use App\Service\ImageUploaderService;
use  Doctrine\ORM\EntityManagerInterface;

use Doctrine\Persistence\ObjectManager;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AdminPropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(PropertyRepository $repository, EntityManagerInterface $em){
        $this->repository =$repository;
        $this->em=$em;
    }

    /**
     * @Route("/admin/create", name="admin.property.create")
     */
    public function new(ImageUploaderService $imageUploaderService,
                        $uploadPersonneDirectory, Request $request){
        $property= new Property();
        $form=$this->createForm(PropertyType::class,$property);
        $form->handleRequest($request);
        if ($form->isSubmitted()&&$form->isValid())
        {
            $imageInfos = $form->get('path')->getData();

            if ($imageInfos) {
                $newImageName = $imageUploaderService->uploadFile($imageInfos, $uploadPersonneDirectory);
                $property->setPath('uploads/property/'.$newImageName);
            }
            $this->em->persist($property);
            $this->em->flush();
            $this->addFlash('success', 'Propriété a été ajouté avec succès');
            return $this->redirectToRoute('admin.property.index');
        }
        return $this->render('admin_property/new.html.twig',[
            'property'=>$property,
            'form'=>$form->createView(),
        ]);

    }
    /**
     * @Route("/admin", name="admin.property.index")
     */
    public function index(): Response
    {
        $properties=$this->repository->findAll();
        return $this->render('admin_property/index.html.twig', [
            'controller_name' => 'AdminPropertyController',
            'properties'=>$properties,
        ]);
    }
    /**
     * @Route("/admin/edit/{id}", name="admin.property.edit", methods="GET|POST")
     */
    public function edit(ImageUploaderService $imageUploaderService,
                         $uploadPersonneDirectory,Property $property, Request $request): Response {

        $form=$this->createForm(PropertyType::class,$property);
        $form->handleRequest($request);
        if ($form->isSubmitted()&&$form->isValid()){
            $imageInfos = $form->get('path')->getData();

            if ($imageInfos) {
                $newImageName = $imageUploaderService->uploadFile($imageInfos, $uploadPersonneDirectory);
                $property->setPath('uploads/property/'.$newImageName);
            }
            $this->em->flush();
            $this->addFlash('success', 'Propriété a été modifié avec succès');
            return $this->redirectToRoute('admin.property.index');
        }
        return $this->render('admin_property/edit.html.twig',[
            'property'=>$property,
            'form'=>$form->createView(),
        ]);
    }

    /**
     * @Route("/admin/edit/{id}", name="admin.property.delete" , methods="DELETE")
     * @param Property $property
     * @param Request $request
     * @return Response
     */
    public function delete(Property $property, Request $request): Response{
        $this->em->remove($property);
        $this->em->flush();
        $this->addFlash('success', 'Propriété a été supprimé avec succès');
        return $this->redirectToRoute('admin.property.index');
    }
}   

templates/admin_property/_form.html.twig
{{form_start(form)}}
<div class="row">
    <div class="col-md-4">
        {{form_row(form.title)}}
    </div>
    <div class="col-md-4">
        {{form_row(form.surface)}}
    </div>

</div>
<div class="row">
    <div class="col-md-2">
        {{form_row(form.rooms)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.bedrooms)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.floor)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.heat)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.type)}}
    </div>
</div>
<div class="row">
    <div class="col-md-5">
        {{form_row(form.address)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.ville)}}
    </div>
    <div class="col-md-2">
        {{form_row(form.postal_code)}}
    </div>


</div>
<div class="row">
    <div class="col-md-2">
        {{form_row(form.price)}}
    </div>

</div>
<div class="row">

    <div class="col-md-4">
        {{form_row(form.location)}}
    </div>

</div>


{{form_rest(form)}}
<button class="btn btn-primary" >{{ button|default('Enregistrer') }}</button>
{{form_end(form)}}

templates/admin_property/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Editer le bien {% endblock %}

{% block body %}


<div class="container mt-4">
    <h2>Editer le bien</h2> 
    <div class="float-right">

    </div>
    <div class="col-md-4">
        {{form_row(form.sold)}}
    </div>
    {{include ('admin_property/_form.html.twig', {form: form, button:'Editer'})}}
    
</div>
{% endblock %}

templates/admin_property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gérer nos biens {% endblock %}

{% block body %}


<div class="container mt-4">
  {% if app.user %}
    <div class="mb-3">
    Bonjour {{ app.user.username }}, Appuyez là pour  <a href="{{ path('admin.contact.edit',{id: 1}) }}">Modifier votre contact</a>
  </div>
  {% endif %}
    <h2>Gérer nos biens</h2>
  <div class="text-right ">
    <a class="btn btn-warning" href="{{path('admin.property.create')}}">Créer un nouveau bien</a>
  </div>
<table class=" table" id="tablex">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#id</th>
      <th scope="col">Titre</th>
      <th scope="col">Ville</th>
      <th scope="col">Nature</th>
      <th scope="col">Type</th>
      <th scope="col">Actions</th>
      
    </tr>
  </thead>
  <tbody>
  {%for property in properties%}
    <tr {% if property.sold >0 %} class="table-warning" {% else %}td class="table-success" {% endif %}>
      <td scope="row">{{property.id}}</td>
      
      <td>{{property.title}}</td>
      <td>{{property.ville}}</td>
      <td>{% if property.location >0 %}Location {% else %} Vente {% endif %}</td>
      <td>{{property.type}}</td>

      <td><a href="{{path('admin.property.edit',{id:property.id})}}" class="btn btn-info"> Editer</a>
          <form method="post" action="{{ path('admin.property.delete',{id: property.id}) }}" style="display: inline-block" onsubmit="return confirm('Supprimer la propriété {{property.title}}??')">
            <input type="hidden" name="_method" value="DELETE">

            <button type="submit" class="btn btn-danger">Supprimer ce bien</button>
          </form> </td>
      
    </tr>
    {%endfor%}
    
   
  </tbody>
</table>


</div>
  <script >
    $(document).ready(function() {
      $('#tablex').DataTable(

              {
                "aLengthMenu": [[5, 10, 25, -1], [5, 10, 25, "All"]],
                "iDisplayLength": 5
              }
      );
    } );
  </script>
{% endblock %}

templates/admin_property/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter le nouveau bien {% endblock %}

{% block body %}


    <div class="container mt-4">
        <h2>Ajouter le nouveau bien</h2>
        {{include ('admin_property/_form.html.twig', {form: form, button:'Ajouter'})}}

    </div>
{% endblock %}